(() => {
    const dom = {
        dragOverlay: document.getElementById('drag-overlay'),
        live2dContainer: document.getElementById('live2d-container'),
        live2dCanvas: document.getElementById('live2d-canvas'),
        hudLayer: document.getElementById('hud-layer'),
        statusChip: document.getElementById('status-chip'),
        statusDot: document.getElementById('status-dot'),
        statusText: document.getElementById('status-text'),
        subtitleBar: document.getElementById('subtitle-bar'),
        inputOverlay: document.getElementById('input-overlay'),
        miniInput: document.getElementById('mini-input'),
        miniSendBtn: document.getElementById('mini-send-btn'),
        controlPanel: document.getElementById('control-panel'),
        toggleInputBtn: document.getElementById('toggle-input-btn'),
        micBtn: document.getElementById('mic-btn'),
        observerBtn: document.getElementById('observer-btn'),
        motionBtn: document.getElementById('motion-btn'),
        recentHistoryBtn: document.getElementById('recent-history-btn'),
        workbenchBtn: document.getElementById('workbench-btn'),
        ttsBtn: document.getElementById('tts-btn'),
        settingsBtn: document.getElementById('settings-btn'),
        closeBtn: document.getElementById('close-btn'),
        imageUpload: document.getElementById('image-upload'),
        imgBtn: document.getElementById('img-btn'),
        settingsModal: document.getElementById('settings-modal'),
        workspaceRootInput: document.getElementById('workspace-root-input'),
        selectWorkspaceDirBtn: document.getElementById('select-workspace-dir-btn'),
        serverIpInput: document.getElementById('server-ip-input'),
        observerModeSelect: document.getElementById('observer-mode-select'),
        accessTokenInput: document.getElementById('access-token-input'),
        toggleTokenVisibilityBtn: document.getElementById('toggle-token-visibility-btn'),
        settingsBackdrop: document.getElementById('settings-backdrop'),
        adminPanelInfo: document.getElementById('admin-panel-info'),
        openAdminPanelLink: document.getElementById('open-admin-panel-link'),
        runtimeConfigStatus: document.getElementById('runtime-config-status'),
        saveSettingsBtn: document.getElementById('save-settings-btn'),
        cancelSettingsBtn: document.getElementById('cancel-settings-btn'),
        chatSection: document.getElementById('chat-section'),
        chatContainer: document.getElementById('chat-container'),
        tracePanel: document.getElementById('trace-panel'),
        traceList: document.getElementById('trace-list'),
        traceDebugToggle: document.getElementById('trace-debug-toggle'),
        copyTraceBtn: document.getElementById('copy-trace-btn'),
        detachTraceBtn: document.getElementById('detach-trace-btn'),
        clearTraceBtn: document.getElementById('clear-trace-btn'),
        traceResizer: document.getElementById('trace-resizer'),
        messageInput: document.getElementById('message-input'),
        sendBtn: document.getElementById('send-btn'),
        inputArea: document.getElementById('input-area'),
        copyTurnBtn: document.getElementById('copy-turn-btn'),
        clearWorkbenchHistoryBtn: document.getElementById('clear-workbench-history-btn'),
        closeWorkbenchBtn: document.getElementById('close-workbench-btn'),
        recentHistoryPanel: document.getElementById('recent-history-panel'),
        recentHistoryList: document.getElementById('recent-history-list'),
        closeRecentHistoryBtn: document.getElementById('close-recent-history-btn')
    };

    window.dom = dom;
})();
